print("\n ********************")
print("\n *****   MENU   *****")
print("\n ********************")
print("\n 1 - cadastra dados do cliente U")
print("\n 2 - cadastra milhagem do cliente ")
print("\n 3 - lista milhagem do cliente II")
print("\n 4 - imprime os nomes que tem maior e menor milhagem")
print("\n 5 - imprime os nomes e as milhagens")
print("\n 6 - SAIR")
input("\nOPCAO :") 